- name: filters
  hosts: web
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "Hi {{ man | default('hani')}}"

  - name: convert string to list
    vars:
     fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: "Fruits are : {{fruits| split(',')}}"

  - name: convert map to list
    vars:
     Details:
      Name: Harini
      City: Guntur
    ansible.builtin.debug:
     msg: "List is: {{Details | dict2items }}"

  - name: list to map
    hosts: web
    tasks: 
    - name: list to map
      vars:
       Details:
        {'key': 'Name', 'value': 'Harini'}
        {'key': 'City', 'value': 'Guntur'}
      ansible.builtin.debug:
       msg: "map is: {{Details | items2dict}} "

