- name: filters
  hosts: web
  tasks:
  - name: default variable
    ansible.builtin.debug:
     msg: "Hi {{ man | default('hani')}}"

  - name: convert string to list
    vars:
     fruits: "apple, banana, orange" #string
    ansible.builtin.debug:
      msg: "Fruits are : {{fruits| split(',')}}"

  - name: convert map to list
    vars:
     Details:
      Name: Harini
      City: Guntur
    ansible.builtin.debug:
     msg: "List is: {{Details | dict2items }}"

   
  - name: list to map
    vars:
      Details:
        - {'key': 'Name', 'value': 'Harini'}
        - {'key': 'City', 'value': 'Guntur'}
    ansible.builtin.debug:
       msg: "map is: {{Details | items2dict}} "

  - name: lowercase
    vars:
     Name: "HARINI"
    ansible.builtin.debug:
     msg: "Name is {{Name | lower}}" 

  - name: upper case
    vars:
     Name: harini
    ansible.builtin.debug:
     msg: "Nmae is {{Name | upper}}"   

  - name: maxi
    vars:
     Num: [1,2,5,89,90,76,56]
    ansible.builtin.debug:
     msg: "Maxi is {{Num | max}}, Mini is {{Num | min}}"

  - name: validipcheck
    vars:
     ip: "34.207.122.5444"
    ansible.builtin.debug:
     msg: "ip is {{ip | ansible.utils.ipaddr}}"


