- name: print
  hosts: local
  connection: local
  tasks:
  - name: play1
    ansible.builtin.debug:
     msg: "Hello from play1 and task1"

- name: print
  hosts: local
  connection: local
  tasks:
  - name: play2
    ansible.builtin.debug:
     msg: "Hi from play2 and task1"
   