- name: install nginx
  hosts: all
  become: yes
  serial: 4
  tasks:
  - name: install
    ansible.builtin.package:
     name: nginx
     state: present
  - name: enable
    ansible.builtin.service:
     name: nginx
     state: started