- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute
    #ansible.builtin.command:  ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
     
  - name: execuye1
    #ansible.builtin.command: ls -ltr
    ansible.builtin.command: ls -ltrrr
    register: command_result

  - name: print output
    ansible.builtin.debug:
     msg: print "{{command_result}}"