- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: commandline
    #ansible.builtin.command:  ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
     