- name: variables
  hosts: local
  connection: local
  vars: #playbook varables- global variables
   Name: Harini
   city: Guntur
  tasks: 
  - name: print
    ansible.builtin.debug:
     msg: "My name is {{Name}} and lives in {{city}}"
   
  - name: print
    vars: #task level variables-local variables
     Name: sai
     city: Chow
    ansible.builtin.debug:
     msg: "My name is {{Name}} and lives in {{city}}"
   