- name: remove existing directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{app_location}}" # backend folder is /app, frontend /usr/share/nginx/html
    state: absent


- name: create directory
  tags:
  - deployment
  ansible.builtin.file:
    state: directory
    path: "{{app_location}}" #backend: /app, frontend: /usr/share/nginx/html/ 
  
- name: unzip the code
  tags:
  - deployment
    ansible.builtin.unarchive:
     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{component}}-v2.zip
     dest: "{{app_location}}" #backend: /app, frontend: /usr/share/nginx/html/
     remote_src : yes
