- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    subnet_id: subnet-0cbb1c995adc71b95
    instance_type: t3.micro
    security_group: sg-01794459d60b74295
  tasks:
  - name: install boto libraries
    ansible.builtin.pip:
     name: "{{item}}"
     executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2
    amazon.aws.ec2_instance:
     name: "{{item}}"
     image_id: "{{ami_id}}"
     subnet_id: "{{subnet_id}}"
     instance_type: "{{instance_type}}"
     security_group: "{{security_group}}"
    loop:
     - mysql
     - backend
     - frontend

  
       
       
     